# ========================
# Common Config
# ========================
spring.application.name=order-service
server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# ========================
# DB Config
# ========================
#db
#spring.datasource.url=jdbc:mysql://localhost:3306/user-db?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=password

# HikariCP connection pool settings (Spring Boot's default)
#spring.datasource.hikari.maximum-pool-size=20
#spring.datasource.hikari.minimum-idle=5
#spring.datasource.hikari.idle-timeout=300000
#spring.datasource.hikari.pool-name=SpringBootJPAHikariCP
#spring.datasource.hikari.max-lifetime=1200000
#spring.datasource.hikari.connection-timeout=30000

# JPA settings
#spring.jpa.hibernate.ddl-auto=update
# Options: create, create-drop, update, validate, none

# Show SQL queries in console (disable in production)
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# Database dialect (usually auto-detected)
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# or for PostgresSQL: org.hibernate.dialect.PostgresSQLDialect

# Naming strategy
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# ========================
# Circuit Breaker Config (Using Resilience)
# ========================
resilience4j.circuitbreaker.instances.orderRefresh.failureRateThreshold=50
resilience4j.circuitbreaker.instances.orderRefresh.minimumNumberOfCalls=10
resilience4j.circuitbreaker.instances.orderRefresh.slidingWindowSize=20
resilience4j.circuitbreaker.instances.orderRefresh.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.orderRefresh.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.orderRefresh.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.orderRefresh.automaticTransitionFromOpenToHalfOpenEnabled=true
# ========================
# Retry Config (Using Resilience)
# ========================
resilience4j.retry.instances.orderRefreshRetry.maxAttempts=3
resilience4j.retry.instances.orderRefreshRetry.waitDuration=2s
resilience4j.retry.instances.orderRefreshRetry.retryExceptions[0]=java.io.IOException
resilience4j.retry.instances.orderRefreshRetry.retryExceptions[1]=java.net.SocketTimeoutException
# ========================
# Logging
# ========================
#For structured logging in the console
logging.level.org.springframework=DEBUG
logging.pattern.console=%clr(%d{HH:mm:ss}){yellow} %clr([${spring.application.name}]){magenta} %clr(%level){blue}: %msg%n
#For structured logging in File
logging.structured.format.file=ecs
logging.file.name=logs/order-services.log
