spring.application.name=discovery-server

eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
server.port=8761

# logging
logging.level.org.springframework=DEBUG
logging.pattern.console=%clr(%d{HH:mm:ss}){yellow} %clr([${spring.application.name}]){magenta} %clr(%level){blue}: %msg%n
#for structured logging
logging.structured.format.file=ecs
logging.file.name=logs/eureka-server.log