spring.application.name=gateway
server.port=8080
jwt.secret=ODg1ZWFkY2ItZDQ1NS00NzNiLWIwMjAtMzI3YTQ2ZmY5NDZk

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
#eureka.instance.prefer-ip-address=true

#Discovery server route
spring.cloud.gateway.mvc.routes[0].id=discovery-server
spring.cloud.gateway.mvc.routes[0].uri=http://localhost:8761/
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/eureka/web
spring.cloud.gateway.mvc.routes[0].filters[0]=SetPath=/

# Route configuration for user-services
spring.cloud.gateway.mvc.routes[1].id=user-services
spring.cloud.gateway.mvc.routes[1].uri=http://localhost:8081/
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/v1/user/**

# Route configuration for order-services
spring.cloud.gateway.mvc.routes[2].id=order-service
spring.cloud.gateway.mvc.routes[2].uri=http://localhost:8082/
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/v1/order/**
#
#spring.cloud.gateway.routes[2].id=secured_apis
#spring.cloud.gateway.routes[2].uri=http://localhost:8081
#spring.cloud.gateway.routes[2].predicates[0]=Path=/**
#spring.cloud.gateway.routes[2].filters[0]=RemoveRequestHeader=Cookie


# logging
logging.level.org.springframework=DEBUG
logging.pattern.console=%clr(%d{HH:mm:ss}){yellow} %clr([${spring.application.name}]){magenta} %clr(%level){blue}: %msg%n
#for structured logging
logging.structured.format.file=ecs
logging.file.name=logs/gateway.log