FROM amazoncorretto:17-alpine-jdk
MAINTAINER Harsh
COPY target/user-services-0.0.1-SNAPSHOT.jar user-services-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/user-services-0.0.1-SNAPSHOT.jar"]
EXPOSE 8081